name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI for Pull Request
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        path: src

    - name: CI
      uses: BluezTestBot/action-ci@master
      with:
        src_path: src
        bluez_path: ""
        output_path: ""
        space: user
        github_token: ${{ secrets.ACTION_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
        patchwork_token : ${{ secrets.PATCHWORK_TOKEN }}

